# Generated by Django 5.2 on 2025-05-04 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AlterModelOptions(
            name='exchangeproposal',
            options={'verbose_name': 'Предложение обмена', 'verbose_name_plural': 'Предложения обмена'},
        ),
    ]
