# Generated by Django 5.2 on 2025-05-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_searchquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquery',
            name='ads',
            field=models.ManyToManyField(blank=True, to='ads.ad'),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='proposals',
            field=models.ManyToManyField(blank=True, to='ads.exchangeproposal'),
        ),
    ]
