# Generated by Django 5.2 on 2025-05-04 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_searchquery_ads_searchquery_proposals'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchQuery',
        ),
    ]
